/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.68
 * Generated at: 2021-08-08 13:04:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.vo.*;

public final class board_005freply_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Include/header.jsp", Long.valueOf(1628426526137L));
    _jspx_dependants.put("/Include/footer.jsp", Long.valueOf(1628083082503L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>JSL 인재 개발원</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	* {margin:0; padding:0;}\r\n");
      out.write("	ul,li {list-style:none;}\r\n");
      out.write("	a {text-decoration:none; color:#fff;}\r\n");
      out.write("	body {background:url(\"img/aa.jfif\");background-repeat:y-repeat;background-size:100%;overflow:auto;height:1000px;}\r\n");
      out.write("	.content {padding:16px; height:300px;}\r\n");
      out.write("	.title {text-align:center;padding:22px;}\r\n");
      out.write("	.content table{width:700px;margin:0 auto;}\r\n");
      out.write("	.content table th {width:20%; border:1px solid #bbb;}\r\n");
      out.write("	.content table td {padding:5px 5px;border:1px solid #bbb;}\r\n");
      out.write("	.content table .btn_group {text-align:center;}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("	function send() {\r\n");
      out.write("		if(board.name.value == \"\") {\r\n");
      out.write("			alert(\"이름을 입력해 주세요.\");\r\n");
      out.write("			board.name.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		if(board.subject.value == \"\") {\r\n");
      out.write("			alert(\"제목을 입력해 주세요.\");\r\n");
      out.write("			board.subject.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		if(board.contents.value == \"\") {\r\n");
      out.write("			alert(\"내용을 입력해 주세요.\");\r\n");
      out.write("			board.contents.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		if(board.pass.value == \"\") {\r\n");
      out.write("			alert(\"비밀번호를 입력해 주세요.\");\r\n");
      out.write("			board.pass.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		alert(\"글을 등록합니다.\")\r\n");
      out.write("		board.action = \"board_reply?page=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("		board.submit();\r\n");
      out.write("	}\r\n");
      out.write("	function cal() {\r\n");
      out.write("		document.getElementById('result').value = document.getElementById(\"contents\").value.length;\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");

	MemberVO loginvo = null;
	if(session.getAttribute("vo") != null) {
		loginvo = (MemberVO)session.getAttribute("vo");
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	.logo {color:#fff; text-align:center; background-color:#5858FA; padding:16px 0;}\r\n");
      out.write("	.nav {padding:12px 90px; overflow:hidden; background-color:#A9A9F5;}\r\n");
      out.write("	.nav ul li {float:left; padding:0 45px; text-align:center; color:#fff;}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("	function logout() {\r\n");
      out.write("		 if (confirm(\"로그아웃 하시겠습니까?\")) {\r\n");
      out.write("		 	location.replace(\"logout\");\r\n");
      out.write("		 }\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"header\">\r\n");
      out.write("		<header>\r\n");
      out.write("			<h1 class=\"logo\"> JSL 인재 개발원  </h1>\r\n");
      out.write("			<div class=\"nav\">\r\n");
      out.write("				<nav>\r\n");
      out.write("					<ul class=\"navi\">\r\n");
      out.write("						<li><a href=\"index\">[홈으로]</a></li>\r\n");
      out.write("					");

						if(loginvo != null) {
					
      out.write("\r\n");
      out.write("						<li><a href=\"javascript:logout()\">[로그아웃]</a></li>\r\n");
      out.write("					");

						} else {
					
      out.write("\r\n");
      out.write("						<li><a href=\"login_form\">[로그인]</a></li>\r\n");
      out.write("					");

						}
					
      out.write("\r\n");
      out.write("						<li><a href=\"board_list\">[자유게시판]</a></li>\r\n");
      out.write("						<li><a href=\"pds_list\">[자료실(회원전용)]</a></li>\r\n");
      out.write("					");

						if(loginvo != null) {
					
      out.write("\r\n");
      out.write("						<li><a href=\"member_modify\">[회원정보수정]</a></li>\r\n");
      out.write("					");

						} else {
					
      out.write("\r\n");
      out.write("						<li><a href=\"member_insert\">[회원가입]</a></li>\r\n");
      out.write("					");

						}
						if(loginvo != null) {
					
      out.write("	\r\n");
      out.write("						<li><a href=\"member_view\">[");
      out.print( loginvo.getName() );
      out.write(" 님]</a></li>\r\n");
      out.write("					");

						} else {
					
      out.write("\r\n");
      out.write("						<li>[guest 님]</li>\r\n");
      out.write("					");

						}
					
      out.write("\r\n");
      out.write("						<li><a href=\"map.jsp\">[오시는길]</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</nav>\r\n");
      out.write("			</div>\r\n");
      out.write("		</header>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	<div class=\"section\">\r\n");
      out.write("		<section>\r\n");
      out.write("			<div class=\"content\">\r\n");
      out.write("				<h2 class=\"title\"> 자유게시판 </h2>\r\n");
      out.write("			<form name=\"board\" method=\"post\">\r\n");
      out.write("			<input type=\"hidden\" name=\"userid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("			<input type=\"hidden\" name=\"idx\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("			<input type=\"hidden\" name=\"reply\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reply}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("				<table>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>작성자</th>\r\n");
      out.write("						<td><input type=\"text\" name=\"name\" maxlength=\"3\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"width:300px;height:30px;font-size:20px;\"></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>이메일</th>\r\n");
      out.write("						<td><input type=\"text\" name=\"email\" maxlength=\"30\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"width:300px;height:30px;font-size:20px;\"></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>제목</th>\r\n");
      out.write("						<td><input type=\"text\" name=\"subject\" maxlength=\"50\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${subject}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"width:300px;height:30px;font-size:20px;\"></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>내용</th>\r\n");
      out.write("						<td><textarea rows=\"10\" name=\"contents\" id=\"contents\" cols=\"60\" maxlength=\"1000\" onkeydown=\"cal()\" onkeyup=\"cal()\" onkeypress=\"cal()\" style=\"overflow:auto; width:500px;height:300px;font-size:20px;\"></textarea><br>\r\n");
      out.write("						<input type=\"text\" id=\"result\" value=\"0\" style=\"width:50px;height:30px;font-size:20px;border:none;background-color:#FBEFEF;\" readonly><font style=\"font-size:20px;\">/1000</font>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>비밀번호</th>\r\n");
      out.write("						<td><input type=\"password\" name=\"pass\" maxlength=\"10\" style=\"width:150px;height:30px;font-size:20px;\"></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td colspan=\"2\" class=\"btn_group\">\r\n");
      out.write("						<input type=\"button\" value=\"글쓰기\" onClick=\"send()\" style=\"width:300px;height:30px;font-size:20px;cursor:pointer;\"> \r\n");
      out.write("						<input type=\"button\" value=\"취소\" onClick=\"history.back()\" style=\"width:300px;height:30px;font-size:20px;cursor:pointer;\">\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("			</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("	</div>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write(".footer {\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  bottom: 0;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  background-color: #A9A9F5;\r\n");
      out.write("  color: white;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  padding:16px 0;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"footer\">\r\n");
      out.write("		<footer>\r\n");
      out.write("			<p>제이에스엘인재개발원주식회사 \r\n");
      out.write("			(대전센터)대전광역시 중구 계룡로 825 (용두동, 희영빌딩) 5층, 7층/ 고객센터: 042-242-4412\r\n");
      out.write("Copyright 제이에스엘인재개발원주식회사. All rights reserved.</p>\r\n");
      out.write("		</footer>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
