/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.68
 * Generated at: 2021-08-08 12:42:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.vo.*;

public final class map_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Include/header.jsp", Long.valueOf(1628426526137L));
    _jspx_dependants.put("/Include/footer.jsp", Long.valueOf(1628083082503L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>JSL 인재 개발원</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	*{margin:0; padding:0;}\r\n");
      out.write("	ul,li {list-style:none;}\r\n");
      out.write("	a {text-decoration:none; color:#fff;}\r\n");
      out.write("	.section {padding-bottom:100px;padding-top:50px;padding-left:300px;padding-right:300px;height:100%;}\r\n");
      out.write("	.title {text-align:center;padding:22px;}\r\n");
      out.write("	body {background:url(\"img/aa.jfif\");background-repeat:y-repeat;background-size:100%;}\r\n");
      out.write("	.title__136144__ p:before {\r\n");
      out.write("	    content: '';\r\n");
      out.write("	    position: absolute;\r\n");
      out.write("	    right: 0;\r\n");
      out.write("	    bottom: 0;\r\n");
      out.write("	    left: 0;\r\n");
      out.write("	    width: 22px;\r\n");
      out.write("	    height: 3px;\r\n");
      out.write("	    margin: 0 auto;\r\n");
      out.write("	    background: #e66d1e;\r\n");
      out.write("	    font-size: 0;\r\n");
      out.write("	}\r\n");
      out.write("	.title__136144__ p {\r\n");
      out.write("	    display: inline-block;\r\n");
      out.write("	    position: relative;\r\n");
      out.write("	    margin: 0;\r\n");
      out.write("	    padding: 0 0 15px;\r\n");
      out.write("	    font-size: 20px;\r\n");
      out.write("	    font-weight: bold;\r\n");
      out.write("	    color: #000000;\r\n");
      out.write("	    letter-spacing: -.03em;\r\n");
      out.write("	    line-height: 1.3em;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");

	MemberVO loginvo = null;
	if(session.getAttribute("vo") != null) {
		loginvo = (MemberVO)session.getAttribute("vo");
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	.logo {color:#fff; text-align:center; background-color:#5858FA; padding:16px 0;}\r\n");
      out.write("	.nav {padding:12px 90px; overflow:hidden; background-color:#A9A9F5;}\r\n");
      out.write("	.nav ul li {float:left; padding:0 45px; text-align:center; color:#fff;}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("	function logout() {\r\n");
      out.write("		 if (confirm(\"로그아웃 하시겠습니까?\")) {\r\n");
      out.write("		 	location.replace(\"logout\");\r\n");
      out.write("		 }\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"header\">\r\n");
      out.write("		<header>\r\n");
      out.write("			<h1 class=\"logo\"> JSL 인재 개발원  </h1>\r\n");
      out.write("			<div class=\"nav\">\r\n");
      out.write("				<nav>\r\n");
      out.write("					<ul class=\"navi\">\r\n");
      out.write("						<li><a href=\"index\">[홈으로]</a></li>\r\n");
      out.write("					");

						if(loginvo != null) {
					
      out.write("\r\n");
      out.write("						<li><a href=\"javascript:logout()\">[로그아웃]</a></li>\r\n");
      out.write("					");

						} else {
					
      out.write("\r\n");
      out.write("						<li><a href=\"login_form\">[로그인]</a></li>\r\n");
      out.write("					");

						}
					
      out.write("\r\n");
      out.write("						<li><a href=\"board_list\">[자유게시판]</a></li>\r\n");
      out.write("						<li><a href=\"pds_list\">[자료실(회원전용)]</a></li>\r\n");
      out.write("					");

						if(loginvo != null) {
					
      out.write("\r\n");
      out.write("						<li><a href=\"member_modify\">[회원정보수정]</a></li>\r\n");
      out.write("					");

						} else {
					
      out.write("\r\n");
      out.write("						<li><a href=\"member_insert\">[회원가입]</a></li>\r\n");
      out.write("					");

						}
						if(loginvo != null) {
					
      out.write("	\r\n");
      out.write("						<li><a href=\"member_view\">[");
      out.print( loginvo.getName() );
      out.write(" 님]</a></li>\r\n");
      out.write("					");

						} else {
					
      out.write("\r\n");
      out.write("						<li>[guest 님]</li>\r\n");
      out.write("					");

						}
					
      out.write("\r\n");
      out.write("						<li><a href=\"map.jsp\">[오시는길]</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</nav>\r\n");
      out.write("			</div>\r\n");
      out.write("		</header>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	<div class=\"section\">\r\n");
      out.write("		<section>\r\n");
      out.write("			<div class=\"row\" style=\"margin-left:auto; margin-right:auto; margin-bottom:80px;background-color:transparent;\">\r\n");
      out.write("				<div style=\"margin:0 auto; padding:0px 0; max-width:1000px;\" class=\"white-space\">\r\n");
      out.write("					<div style=\"margin-top:-0px;margin-left:-0px;\">\r\n");
      out.write("						<div class=\"col d_col_6 t_col_6 m_col_6\" style=\"padding-top:0px;padding-left:0px;\">\r\n");
      out.write("							<div style=\"background-color:#;\">\r\n");
      out.write("								<div style=\"word-break:break-all;margin:0 0px 25px 0px;text-align:center;\">\r\n");
      out.write("									<div class=\"title__136144__\">\r\n");
      out.write("										<p>오시는 길</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row\" style=\"margin-left:auto; margin-right:auto; margin-bottom:40px;background-color:#56606a;\">\r\n");
      out.write("				<div style=\"margin:0 auto; padding:40px 0; max-width:1000px;\" class=\"white-space\">\r\n");
      out.write("					<div style=\"margin-top:-0px;margin-left:-0px;\">\r\n");
      out.write("						<div class=\"col d_col_6 t_col_6 m_col_6\" style=\"padding-top:0px;padding-left:0px;\">\r\n");
      out.write("							<div style=\"background-color:transparent;\">\r\n");
      out.write("								<div style=\"word-break:break-all;margin:0 0px 0px 0px;\">\r\n");
      out.write("									<div class=\"map__24104__\">\r\n");
      out.write("										<iframe src=\"https://www.anybuild.com/sys_load/kakao_map_xy_load.php?center_x=&amp;center_y=&amp;map_h=400&amp;addr=대전광역시 중구 계룡로 825 희영빌딩5F,6F&amp;title=JSL 인재개발원&amp;info=&amp;zoom=10\" width=\"100%\" height=\"400\" frameborder=\"0\" scrolling=\"no\" id=\"google_map__24104__\" name=\"google_map__24104__\" style=\"height: 400px;\"></iframe>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row\" style=\"margin-left:auto; margin-right:auto; margin-bottom:0px;background-color:transparent;\">\r\n");
      out.write("				<h4><font color=\"#5858FA\">☎ 대표전화</font> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 042-242-4412</h4>\r\n");
      out.write("				<h4><font color=\"#5858FA\">■ 메일</font> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; cmk@jslhrd.com</h4>\r\n");
      out.write("				<h4><font color=\"#5858FA\">※ 업무시간</font> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 월~금 09:00 ~ 18:00</h4>\r\n");
      out.write("				<h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 점심 12:00 ~ 13:00</h4>\r\n");
      out.write("				<h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 주말 Closed</h4>\r\n");
      out.write("				<h4><font color=\"#5858FA\">▶ 주소</font> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 대전광역시 중구 계룡로 825 희영빌딩 5F, 7F</h4>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write(".footer {\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  bottom: 0;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  background-color: #A9A9F5;\r\n");
      out.write("  color: white;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  padding:16px 0;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"footer\">\r\n");
      out.write("		<footer>\r\n");
      out.write("			<p>제이에스엘인재개발원주식회사 \r\n");
      out.write("			(대전센터)대전광역시 중구 계룡로 825 (용두동, 희영빌딩) 5층, 7층/ 고객센터: 042-242-4412\r\n");
      out.write("Copyright 제이에스엘인재개발원주식회사. All rights reserved.</p>\r\n");
      out.write("		</footer>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
