/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.68
 * Generated at: 2021-09-10 02:24:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class member_005fmail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>협력업체 관리 - 관리자페이지</title>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n");
      out.write("<style type=\"text/css\">\n");
      out.write("<!--\n");
      out.write("body,td,th {\n");
      out.write("	font-size: 12px;\n");
      out.write("	color: #606060;\n");
      out.write("}\n");
      out.write("body {\n");
      out.write("	margin-left: 0px;\n");
      out.write("	margin-top: 0px;\n");
      out.write("}\n");
      out.write("-->\n");
      out.write("</style>\n");
      out.write("<script>\n");
      out.write("	function send() {\n");
      out.write("		if(mail.subject.value == \"\") {\n");
      out.write("			alert(\"제목을 입력해주세요.\");\n");
      out.write("			mail.subject.focus();\n");
      out.write("			return;\n");
      out.write("		}\n");
      out.write("		if(mail.contents.value == \"\") {\n");
      out.write("			alert(\"내용을 입력해주세요.\");\n");
      out.write("			mail.contents.focus();\n");
      out.write("			return;\n");
      out.write("		}\n");
      out.write("		mail.action = \"member_mail_pro.do\";\n");
      out.write("		mail.submit();\n");
      out.write("	}\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<form name=\"mail\" method=\"post\">\n");
      out.write("<input type=\"hidden\" name=\"list\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("	<tr><td>");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "top_menu.jsp", out, true);
      out.write("</td></tr>\n");
      out.write("	<tr>\n");
      out.write("		<td align=\"center\" height=\"100%\" valign=middle><br>\n");
      out.write("			<table width=\"30%\" border=\"1\" cellspacing=\"0\" cellpadding=\"3\" bgcolor=\"#FFCC66\" bordercolor=\"#FFFFFF\" bordercolorlight=\"#000000\">\n");
      out.write("				<tr> \n");
      out.write("					<td height=40 align=\"center\" style=\"font-size: 15px;\"><b>단체 메일 보내기</b></a>\n");
      out.write("					</b></td>\n");
      out.write("				</tr>\n");
      out.write("			</table><br>\n");
      out.write("			<table width=\"60%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("				<tr>\n");
      out.write("					<td><table width=\"100%\" border=\"0\" cellpadding=\"6\" cellspacing=\"1\" bgcolor=\"DDDDDD\">\n");
      out.write("							<tr>\n");
      out.write("								<td width=\"20%\" align=\"center\" bgcolor=\"EcECEC\"><strong>제목</strong></td>\n");
      out.write("								<td bgcolor=\"ffffff\"><input name=\"subject\" type=\"text\" style=\"width:350; height:18; padding:2; border:1 solid slategray\" size=\"120\"></td>\n");
      out.write("							</tr>\n");
      out.write("							<tr bgcolor=\"EcECEC\">\n");
      out.write("								<td align=\"center\" bgcolor=\"EcECEC\"><strong>내용</strong></td>\n");
      out.write("								<td bgcolor=\"ffffff\">\n");
      out.write("										<textarea name=\"contents\" cols=\"62\" rows=\"10\" class=\"textfield\"> </textarea>\n");
      out.write("								</td>\n");
      out.write("							</tr>\n");
      out.write("						</table>\n");
      out.write("					</td>\n");
      out.write("				</tr>\n");
      out.write("			</table><br>\n");
      out.write("			<table width=\"60%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("				<tr>\n");
      out.write("					<td align=center><a href=\"javascript:send()\"><b>[전송]</b></a>&nbsp; <a href=\"javascript:history.back()\"><b>[취소]</b></a></td>\n");
      out.write("				</tr>\n");
      out.write("			</table>\n");
      out.write("		</td>\n");
      out.write("	</tr>\n");
      out.write("</table>\n");
      out.write("</form>	\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
