/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.68
 * Generated at: 2021-08-13 07:55:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Sample2;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Sample2/footer.jsp", Long.valueOf(1628835679137L));
    _jspx_dependants.put("/Sample2/header.jsp", Long.valueOf(1628837278398L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<title>장수하늘소</title>\r\n");
      out.write("	<link href=\"/Sample2/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css\">\r\n");
      out.write("	<link href=\"/Sample2/css/common.css\" rel=\"stylesheet\">\r\n");
      out.write("	<link href=\"/Sample2/css/mystyle.css\" rel=\"stylesheet\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <script>\r\n");
      out.write("    $(function(){\r\n");
      out.write("    	\r\n");
      out.write("      $('.slider').bxSlider({\r\n");
      out.write("    	  mode: 'fade',\r\n");
      out.write("    	  captions: true\r\n");
      out.write("      });\r\n");
      out.write("      \r\n");
      out.write("      $(\".sitemap\").click(function() {\r\n");
      out.write("			$(\".sitewrap\").slideDown();\r\n");
      out.write("		})\r\n");
      out.write("	  $(\"#close\").click(function() {\r\n");
      out.write("			$(\".sitewrap\").slideUp();\r\n");
      out.write("		})\r\n");
      out.write("		\r\n");
      out.write("	  $(\".nav > nav > .navi > li\").hover(function() {\r\n");
      out.write("		  $(this).children(\".navi2\").stop().slideDown();\r\n");
      out.write("	  }, function() {\r\n");
      out.write("		  $(this).children(\".navi2\").stop().slideUp();\r\n");
      out.write("	  });\r\n");
      out.write("		\r\n");
      out.write("    });\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"header\">\r\n");
      out.write("		<header>\r\n");
      out.write("			<div class=\"topnav\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"/Sample2/member/login.jsp\">로그인</a></li>\r\n");
      out.write("					<li><a href=\"/Sample2/member/member.jsp\">회원가입</a></li>\r\n");
      out.write("					<li><a href=\"javascript:void(0)\" class=\"sitemap\">사이트맵</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"navigation\">\r\n");
      out.write("				<h1 class=\"logo\"><a href=\"/Sample2/index.jsp\">LOGO</a></h1>\r\n");
      out.write("				<div class=\"nav\">\r\n");
      out.write("					<nav>\r\n");
      out.write("						<ul class=\"navi\">\r\n");
      out.write("							<li><a href=\"/Sample2/about/about.jsp\">내소개</a>\r\n");
      out.write("								<ul class=\"navi2\">\r\n");
      out.write("									<li><a href=\"#\">이력서</a></li>\r\n");
      out.write("									<li><a href=\"#\">자기소개서</a></li>\r\n");
      out.write("									<li><a href=\"#\">자격증</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li><a href=\"/Sample2/gallery/gallery.jsp\">갤러리</a>\r\n");
      out.write("								<ul class=\"navi2\">\r\n");
      out.write("									<li><a href=\"#\">포토샵</a></li>\r\n");
      out.write("									<li><a href=\"#\">일러스트</a></li>\r\n");
      out.write("									<li><a href=\"#\">개인작품</a></li>\r\n");
      out.write("									<li><a href=\"#\">웹갤러리</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li><a href=\"/Sample2/portfolio/portfolio.jsp\">포트폴리오</a>\r\n");
      out.write("								<ul class=\"navi2\">\r\n");
      out.write("									<li><a href=\"#\">앱개발</a></li>\r\n");
      out.write("									<li><a href=\"#\">웹개발</a></li>\r\n");
      out.write("									<li><a href=\"#\">UI디자인</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li><a href=\"/Sample2/qa/qa.jsp\">질문답변</a>\r\n");
      out.write("								<ul class=\"navi2\">\r\n");
      out.write("									<li><a href=\"#\">JAVA</a></li>\r\n");
      out.write("									<li><a href=\"#\">DB</a></li>\r\n");
      out.write("									<li><a href=\"#\">JSP</a></li>\r\n");
      out.write("									<li><a href=\"#\">PHP</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li><a href=\"/Sample2/notice/notice.jsp\">공지사항</a></li>\r\n");
      out.write("							<li><a href=\"/Sample2/shop/shop.jsp\">쇼핑몰</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</nav>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</header>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"line\"></div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"sitewrap\">\r\n");
      out.write("		<span class=\"fa fa-close\" id=\"close\" style=\"cursor:pointer\"></span>\r\n");
      out.write("		<div class=\"inner\">\r\n");
      out.write("			<span class=\"map\">내소개</span>\r\n");
      out.write("			<span class=\"map\">갤러리</span>\r\n");
      out.write("			<span class=\"map\">포트폴리오</span>\r\n");
      out.write("			<span class=\"map\">질문답변</span>\r\n");
      out.write("			<span class=\"map\">공지사항</span>\r\n");
      out.write("			<span class=\"map\">쇼핑몰</span>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"slider\">\r\n");
      out.write("	    <div><img src=\"images/a1.jpg\" alt=\"\" title=\"배움의 즐거움이 있는곳\"></div>\r\n");
      out.write("	    <div><img src=\"images/a2.jpg\" alt=\"\" title=\"나에게 주는 만큼\"></div>\r\n");
      out.write("	    <div><img src=\"images/a3.jpg\" alt=\"\" title=\"나에게도 많은 축복이 있습니다\"></div>\r\n");
      out.write("  	</div>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"indexgallery\">\r\n");
      out.write("			<div class=\"indextitle\">\r\n");
      out.write("				<h2>장수하늘소<br>갤러리</h2>\r\n");
      out.write("				<span><a href=\"/gallery/gallery.jsp\">MORE</a></span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"\"><img src=\"images/shop1.jpg\"></a></li>\r\n");
      out.write("				<li><a href=\"\"><img src=\"images/shop2.jpg\"></a></li>\r\n");
      out.write("				<li><a href=\"\"><img src=\"images/shop3.jpg\"></a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"bbs_wrap\">\r\n");
      out.write("		<div class=\"bbs_left\">\r\n");
      out.write("			<h2 class=\"title\">공지시항</h2>\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"#\">화면구현은 어떻게 하는가</a></li>\r\n");
      out.write("				<li><a href=\"#\">홈페이지 혼자 만들어보기</a></li>\r\n");
      out.write("				<li><a href=\"#\">지구여행 얼마 남았는가</a> </li>\r\n");
      out.write("				<li><a href=\"#\">일본취업 나도 해보자</a></li>\r\n");
      out.write("				<li><a href=\"#\">하다보면 할수 있다</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<a href=\"notice.do\"><span class=\"fa fa-plus plus\"></span></a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"bbs_right\">\r\n");
      out.write("			<h2 class=\"title\">질문답변</h2>\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"#\">이클립스 다운로드</a></li>\r\n");
      out.write("				<li><a href=\"#\">JSP강좌 PDF</a></li>\r\n");
      out.write("				<li><a href=\"#\">JAVA 환경설정 파일 설명서</a> </li>\r\n");
      out.write("				<li><a href=\"#\">동영상 강좌 자료실</a></li>\r\n");
      out.write("				<li><a href=\"#\">스프링 강좌 자료 다운</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<a href=\"qa.do\"><span class=\"fa fa-plus plus\"></span></a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("		<footer>\r\n");
      out.write("			<p>&copy; JANGSU. All &nbsp;&nbsp;&nbsp;Rights Reserved.</p>\r\n");
      out.write("		</footer>\r\n");
      out.write("		<!-- &copy; &nbsp; &gt; > &lt;< -->\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
